### ISSUE TITLE
Enabling logSpans flag causes exception

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-client-node#123]
The logging reporter writes the span with `JSON.stringify`, which fails because of some recursive links in the span.

Instead, it should log the span in the same format as other clients, as trace context + operation name.

**Comment by rajeshsegu** [comment]
Is there a reason why we are not using just `util.inspect` since this is a node only framework

```
util.inspect(span, {depth: 3});
```

**Comment by yurishkuro** [comment]
I don't see the need for logging any details of the span itself.  For example, in Go client the log looks like this
```
2017/09/22 20:26:49 Reporting span 5642914c078ef2f0:5642914c078ef2f0:0:1
```
