### ISSUE TITLE
Any hosted solutions available for Jaeger?

### ISSUE THREAD

**Issue by Strandedpirate** [uber/jaeger-client-node#144]
Are there any hosted solutions out there available for Jaeger or opentracing in general?

My company is looking into using Jeager but they don't want to incur the costs of hosting/maintaining the solution themselves.

**Comment by vprithvi** [comment]
I hear http://lightstep.com/ is a good hosted solution!

**Comment by yurishkuro** [comment]
Closing, as it's not an issue. Feel free to ask on the mailing list or gitter.
