### ISSUE TITLE
Consider using Long instead of buffers for IDs

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-client-node#7]
According to @Raynos:

> Keeping i64 in buffer is expensive for numerous reasons, prefer Long format.
>  - buffers should have a "short life time", keeping them around will bloat memory ( they are internally slab allocated )
>  - allocating a buffer slice is more expensive then an object with two integer fields

I see that Long has to/from hex string, so we should be using it instead of buffers:

```
Long#toString(radix=)
Long.fromString(str, unsigned=, radix=)
```

https://www.npmjs.com/package/long#longtostringradix

**Comment by oibe** [comment]
fixed by (dual representation of strings and buffers.) https://github.com/uber/jaeger-client-node/pull/30.
Also using longs did not reveal great benchmarks.  https://github.com/uber/jaeger-client-node/pull/12.
No benchmarks in link above, but I tested locally.
