### ISSUE TITLE
Double reporting process tags?

### ISSUE THREAD

**Issue by black-adder** [uber/jaeger-client-node#90]
We set the process tags for the tracer once on startup here: https://github.com/uber/jaeger-client-node/blob/master/src/tracer.js#L88

These tags include the hostname, ip, etc.

However, in https://github.com/uber/jaeger-client-node/blob/master/src/tracer.js#L138, for the first span in the process, we add the same tags that we've already added in the process.

Does this logic make sense for the jaeger model? Given all the tags that we need are already in the process, is this double tagging necessary?

@badiib you know the converters better than anyone, would this cause an issue if we removed the tags from the first span in the process?
@yurishkuro for philosophical reasons

**Comment by yurishkuro** [comment]
>  https://github.com/uber/jaeger-client-node/blob/master/src/tracer.js#L138

that is not needed. The whole idea of process tags is to avoid having to send them in the spans.
